### ISSUE TITLE
[BUG] Python client docs - missing import when using nested objects

### ISSUE THREAD

**Issue by johnnyaug** [OpenAPITools/openapi-generator#10279]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating python docs where the parameters are nested objects, their classes are not imported.

Example in the pet store docs:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/docs/PetApi.md#find_pets_by_tags

In this file, `Tag` should be imported.

##### openapi-generator version

latest master branch

##### OpenAPI declaration file content or url

In the Petstore example https://github.com/OpenAPITools/openapi-generator/blob/master/samples/yaml/pet.yml,
Pet has a $ref to Tag.

**Comment by spacether** [comment]
Nested imports were fixed in https://github.com/OpenAPITools/openapi-generator/pull/13137
- in python-experimnetal v6.1.0 and later
- and in python in v6.2.0 and later

For the listed case, the Tag schema is defined inline in the endpoint, and it is generated as a Schema class in the endpoint module here: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/paths/pet_find_by_tags/get.py#L59

**Comment by feluelle** [comment]
I am still seeing this with `python-nextgen` 6.5.0 and 6.6.0-SNAPSHOT. Is this only fixed in `python`?

**Comment by spacether** [comment]
Yes. Python-nextgen did not exist when this ticket was created and closed. Please make a separate ticket for python-nextgen
