### ISSUE TITLE
[BUG][JavaSpring] Multipart request regression in 6.x

### ISSUE THREAD

**Issue by cc-ju** [OpenAPITools/openapi-generator#12498]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
It seems the PR #11449 breaks with some multipart requests.

With an endpoint:

* Consuming multipart/form-data
* File as parameter
* A second parameter consisting of an object

and the generator settings:
* `skipFormModel` set to false to use the second parameter
* `interfaceOnly` set to true to only generate models & interfaces

The generated API causes an error while spring tries to convert the request part to the object:

```
Resolved [org.springframework.web.method.annotation.MethodArgumentConversionNotSupportedException: Failed to convert value of type 'java.lang.String' to required type 'com.example.demo.api.model.TestObjectPart'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.example.demo.api.model.TestObjectPart': no matching editors or conversion strategy found]
```

##### openapi-generator version

It's a regression introduced with openapi-generator 6.x.
With the 5.x version the generated code behaves as expected.

##### OpenAPI declaration file content or url
Or see the reproduction repo: https://github.com/cc-ju/openapi-genrator-spring-error-reproduction/blob/main/openapi.yaml
```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: test

paths:
  /test:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              file:
                contentType: "application/octet-stream"
              content:
                contentType: "application/json"
            schema:
              type: object
              required:
                - file
                - content
              properties:
                file:
                  type: string
                  format: binary
                content:
                  $ref: "#/components/schemas/testObjectPart"
      responses:
        200:
          description: OK

components:
  schemas:
    testObjectPart:
      type: object
      required:
        - foo
      properties:
        foo:
          type: string
        bar:
          type: number
```

##### Actual output #####
```
    default ResponseEntity<Void> testPost(
        @Parameter(name = "file", description = "", required = true) @RequestPart(value = "file", required = true) MultipartFile file,
        @Parameter(name = "content", description = "", required = true) @Valid @RequestParam(value = "content", required = true) TestObjectPart content
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```

##### Expected output #####
**Note that this would re-introduce the problem #11449 tried to fix**

```
    default ResponseEntity<Void> testPost(
        @Parameter(name = "file", description = "", required = true) @RequestPart(value = "file", required = true) MultipartFile file,
        @Parameter(name = "content", description = "", required = true) @Valid @RequestPart(value = "content", required = true) TestObjectPart content
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```

##### Steps to reproduce
check out the reproduction repo: https://github.com/cc-ju/openapi-genrator-spring-error-reproduction

run `./gradlew check --info`

To switch to the older generator

##### Related issues/PRs

As mentioned above this regression is caused by #11449

##### Suggest a fix

Obviously #11449 resolved another problem. But broke this use case.
Currently I don't have a solution which does not break either this use case or the use case from the PR.

**Comment by bskorka** [comment]
Noticed the same today, the file is mapped as `@RequestPart`, and companion object is `@RequestParam`. 

JSON definition:
```json
"requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "documentDescription",
                  "document"
                ],
                "properties": {
                  "documentDescription": {
                    "$ref": "#/components/schemas/DocumentDescription"
                  },
                  "document": {
                    "type": "string",
                    "format": "binary",
                    "description": "A document.                      \nCurrently only **application/pdf** Content-Type is supported.\n"
                  }
                }
              },
              "encoding": {
                "documentDescription": {
                  "contentType": "application/json"
                },
                "document": {
                  "contentType": "application/pdf"
                }
              }
            }
          }
        }
```

Generated code:
```java
default Mono<ResponseEntity<Void>> endpoint1(
...
        @Parameter(name = "documentDescription", description = "", required = true) @Valid @RequestParam(value = "documentDescription", required = true) DocumentDescription documentDescription,
        @Parameter(name = "document", description = "A document.                       Currently only **application/pdf** Content-Type is supported. ", required = true) @RequestPart(value = "document", required = true) Flux<Part> document,
...
    ) {
```

Tried to test it:
```java
    @Test
    public void test() {
        DocumentDescription documentDescription = ...
        MultipartBodyBuilder multipartBodyBuilder = new MultipartBodyBuilder();
        multipartBodyBuilder.part("document", new ClassPathResource("/pdf/testFile.pdf"), MediaType.APPLICATION_PDF);
        multipartBodyBuilder.part("documentDescription", documentDescription, MediaType.APPLICATION_JSON);

        testClient.post()
                .uri(uriBuilder -> uriBuilder
                        .path(REQUEST_URL)
                        .queryParam("requestId", "1234")
                        .build()
                )
                .header("header-1", "1")
                .contentType(MediaType.MULTIPART_FORM_DATA)
                .bodyValue(multipartBodyBuilder.build())
                .exchange()
                .expectStatus().isAccepted();
    }
```

And was getting:
```
2022-08-12 17:44:04,479 [jetty-http@25f7cc38-35] DEBUG o.s.web.method.HandlerMethod - [3e4b6cd7] Could not resolve parameter [2] in public reactor.core.publisher.Mono<org.springframework.http.ResponseEntity<java.lang.Void>> xxx.GeneratedController.endpoint1(java.lang.String,java.lang.String,xxx.DocumentDescription,reactor.core.publisher.Flux<org.springframework.http.codec.multipart.Part>,org.springframework.web.server.ServerWebExchange): 400 BAD_REQUEST "Required DocumentDescription parameter 'documentDescription' is not present"
```

After changing the `@RequestParam` to `@RequestPart` for `documentDescription` param - everything is working well for above WebClient tests.

**Comment by FieteO** [comment]
I have solved it by customizing the `formParams.mustache` template to revert the change.

For that, I have copied the file [from the repo](https://github.com/OpenAPITools/openapi-generator/blob/6.1.x/modules/openapi-generator/src/main/resources/JavaSpring/formParams.mustache) (make sure to use the appropriate branch, here `6.1.x`!) and recreated it in `templates/formParams.mustache` in my project.
I have then reverted the change from #11449 by changing `@RequestParam` to `@RequestPart` in the template.

The custom template can then be registered in the `openApiGenerate` task in gradle by adding the `templateDir` option.
``` groovy
openApiGenerate {
  generatorName = "spring"
  library = "spring-boot"
  ...
  templateDir = "$projectDir/templates"
}
```

**Comment by skduma** [comment]
Apparently, reverting changes in the the `formParams.mustache` template is not a solution as it breaks the generated code for content type `application/x-www-form-urlencoded`

The template have to take into account `isMultipart` value when generating `@RequestParam` annotation string.

To solve the issue and seamlessly support following content types in spring generated code
* `application/x-www-form-urlencoded`
* `multipart/*`
The string `@RequestParam` in template should be substituted by 
```
{{#isMultipart}}@RequestPart{{/isMultipart}}{{^isMultipart}}@RequestParam{{/isMultipart}}
```

**Comment by lsh-silpion** [comment]
Ping!

I am also affected by this bug. Any news here?

**Comment by rayalex** [comment]
@lsh-silpion If you update to `6.3.0-SNAPSHOT` it should be fixed. It's a temporary solution at least until `6.3.0` releases.

**Comment by lsh-silpion** [comment]
I enabled snapshots by adding ```

    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </pluginRepository>
    </pluginRepositories>
``` and then used ```
        <openapi-generator-version>6.3.0-20230125.125049-89</openapi-generator-version>
``` specifially (because 6.3.0-SNAPSHOT did not seem to work) and I am still getting ```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project specification: Compilation failure
[ERROR] /Users/lars/Documents/Projects/akquinet/TIMREF/messenger-testtreiber-api/specification/target/generated-sources/openapi/src/main/java/de/akquinet/timref/testdriver/api/DevicesApi.java:[1744,54] Inkompatible Typen: org.springframework.core.io.Resource kann nicht in org.springframework.web.multipart.MultipartFile konvertiert werden

``` 

I am missing something?

**Comment by bjpe** [comment]
Hi, today I also stumpled upon this bug in version `6.5.0` of the `spring` generator. Is there any update?

**Comment by bjpe** [comment]
Hi, the bug still exists in version `7.0.0`.

**Comment by vitaliykushneruk** [comment]
Hi, the bug still exists in version 7.2.0.

**Comment by chucktesejme** [comment]
Hi, same in 7.3.0

**Comment by miensol** [comment]
Hi, I think I encountered this bug in 7.8.0 as well.

**Comment by DanielLuis** [comment]
Hello, I also have this problem in version 7.8.0, after a few attempts I realized that if in the request body the multipart file is together with an object in by reference the two will be generated as @RequestPart.

Example:

Open Api Spec:
```json
"/api/{id}": {
      "post": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": [
                  "Description",
                  "File",
                  "FileId"
                ],
                "type": "object",
                "properties": {
                  "FileId": {
                    "type": "string",
                    "format": "uuid"
                  },
                  "Description": {
                    "maxLength": 5000,
                    "type": "string"
                  },
                  "File": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }
``` 

Wrong generated class: 
```java
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/{id}",
        consumes = { "multipart/form-data" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    
    void apiPost(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID regressId,
        @Parameter(name = "FileId", description = "", required = true) @Valid @RequestParam(value = "FileId", required = true) UUID fileId,
        @Parameter(name = "Description", description = "", required = true) @Valid @RequestParam(value = "Description", required = true) String description,
        @Parameter(name = "File", description = "", required = true) @RequestPart(value = "File", required = true) MultipartFile file
    );
``` 

Possible Workaround:
New Open Api Spec:
```json
"/api/{id}": {
      "post": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
       "requestBody": {
                "content": {
                  "multipart/form-data": {
                    "schema": {
                      "required": [
                        "Document",
                        "File"
                      ],
                      "type": "object",
                      "properties": {
                        "Document" : {
                          "$ref" : "#/components/schemas/DocumentDto"
                        },
                        "File": {
                          "type": "string",
                          "format": "binary"
                        }
                      }
                    }
                  }
                }
              },
components :
      "DocumentDto" : {
        "required" : [ "FileId", "Description"],
        "type" : "object",
        "properties" : {
          "FileId": {
            "type": "string",
            "format": "uuid"
          },
          "Description": {
            "maxLength": 5000,
            "type": "string"
          }
        },
        "description" : "Document JSON content"
      }
``` 

New generated class: 
```java
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/{id}",
        consumes = { "multipart/form-data" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    
    void apiPost(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID regressId,
        @Parameter(name = "Document", description = "", required = true) @Valid @RequestPart(value = "Document", required = true) DocumentDto document,
        @Parameter(name = "File", description = "", required = true) @RequestPart(value = "File", required = true) MultipartFile file
    );
``` 
I hope I've helped you with this workaround while we still don't have a definitive solution.

**Comment by xaume** [comment]
@DanielLuis thanks for the tip. Isn't this the same scenario that @cc-ju mentions in the original bug description? Can we consider it resolved then?

**Comment by Phortran** [comment]
@xaume I'm afraid it cannot be considered resolved because the workaround provided changes the semantic (separated attributes -> attributed bundled in wrapper object). The generator must generate correct code for every spec that is semantically correct.

I can reproduce this bug in version 7.18.0 with the following definition:

```yaml
content:
  multipart/form-data:
    schema:
      type: object
      encoding:
        metadata:
          contentType: application/json
      properties:
        file:
          type: string
          format: binary
        metadata:
          description: Arbitrary JSON metadata for the file
          type: object
          additionalProperties: true
          example:
            owner: bar
            custom_field1: foo
```

in the generated controller I'm getting

```java
    @RequestMapping(
        method = RequestMethod.POST,
        value = "bla",
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<EntryResponse> myMethod(
        @Parameter(name = "file", description = "", required = true) @RequestPart(value = "file", required = true) MultipartFile file,
        @Valid @RequestParam(value = "metadata", required = false) Map<String, Object> metadata
    ) {
        ...
    }
```
in my example `metadata` is an attribute where arbitrary JSON should be allowed. If I manually replace `@RequestParam` with `@RequestPart`, it works.
