### ISSUE TITLE
[BUG][Go] Missing import of 'time' package when model contains object(map) of dates

### ISSUE THREAD

**Issue by mohakkataria** [OpenAPITools/openapi-generator#14403]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Go module generated from a schema property like this:
```
        "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
```
is missing the import time statement and won't compile.

##### OpenAPI declaration file content or url

```json
"/api/v2/Configuration/LatestConfigDates": {
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "Get the latest config update times for each application running on a role.",
        "parameters": [
          {
            "name": "roleId",
            "in": "query",
            "description": "The role to get latest config dates for",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string",
                    "format": "date-time"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
```
  -->

##### Generation Details

openapi-generator generate -g go -i api.yaml -o go/

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/3972

**Comment by philip-ellis-sp** [comment]
I think this is a duplicate of https://github.com/OpenAPITools/openapi-generator/pull/14057

**Comment by christerswahn** [comment]
I'm having this problem as well (and it does not seem to have been fixed by [#14057](https://github.com/OpenAPITools/openapi-generator/pull/)).

**Comment by madpah** [comment]
Same here - the OpenAPI Schema (in YAML) that is choking the generator is:

```
   MyUserDTO:
      properties:
        emailAndCommitDateMap:
          additionalProperties:
            items:
              format: date-time
              type: string
            type: array
          type: object
      type: object
```

Generated model is missing the import for `time`.

**Comment by madpah** [comment]
I can confirm I have [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) and the issue still exists.
