### ISSUE TITLE
[REQ][go] Tempfile is not deleted

### ISSUE THREAD

**Issue by hijiki51** [OpenAPITools/openapi-generator#15131]
### Is your feature request related to a problem? Please describe.

APIClient creates a temporary file when decoding a response, but it is not deleted afterwards. This causes the /tmp directory to become bloated over time, which can lead to performance and storage issues.

ref: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/go/go-petstore/client.go#L480
https://pkg.go.dev/os#CreateTemp

## Describe the solution you'd like

Delete temporary files once it is no longer needed.

**Comment by wing328** [comment]
fixed via #16303

please pull the latest master to give it a try.

**Comment by sethlivingston** [comment]
This issue isn't completely fixed. The temp files remain if an error occurs while writing to them. The call to remove the files needs to be `defer`red so they get removed no matter what:

```go
	if f, ok := v.(*os.File); ok {
		f, err = os.CreateTemp("", "HttpClientFile")
		if err != nil {
			return
		}
		defer os.Remove(f.Name())  // <--- add
		_, err = f.Write(b)
		if err != nil {
			return
		}
		_, err = f.Seek(0, io.SeekStart)
		err = os.Remove(f.Name())  // <-- remove
		return
	}
	if f, ok := v.(**os.File); ok {
		*f, err = os.CreateTemp("", "HttpClientFile")
		if err != nil {
			return
		}
		defer os.Remove(f.Name())  // <--- add
		_, err = (*f).Write(b)
		if err != nil {
			return
		}
		_, err = (*f).Seek(0, io.SeekStart)
		err = os.Remove((*f).Name())  // <-- remove
		return
	}
```

**Comment by wing328** [comment]
@sethlivingston can you please file a PR with the suggested fix?
