### ISSUE TITLE
[BUG] package io.swagger.v3.oas.annotations.media does not exist

### ISSUE THREAD

**Issue by Haarolean** [OpenAPITools/openapi-generator#16932]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generating an example (pet store) [with maven plugin](https://openapi-generator.tech/docs/plugins/) produces the following exception:
`api/dto/ApiResponseDTO.java:[11,43] package io.swagger.v3.oas.annotations.media does not exist`
Additional (required, it seems?) dependencies for plugin are not listed in docs, so I believe it's a bug.

##### openapi-generator version

7.0.1 maven plugin

##### OpenAPI declaration file content or url

https://gist.github.com/Haarolean/8a9b07f74544c7e45d553ff33798ed8c (swagger petstore)

##### Generation Details

maven,
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.0.1</version>
                <executions>
                    <execution>
                        <id>interfaces</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                            <output>${project.build.directory}/generated-sources/api</output>
                            <generatorName>spring</generatorName>
                            <modelNameSuffix>DTO</modelNameSuffix>
                            <configOptions>
                                <modelPackage>lol.memelord.kapybro.api.dto</modelPackage>
                                <apiPackage>lol.memelord.kapybro.api.api</apiPackage>
                                <sourceFolder>test</sourceFolder>
                                <interfaceOnly>true</interfaceOnly>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useBeanValidation>true</useBeanValidation>
                                <useTags>true</useTags>
                                <useSpringBoot3>true</useSpringBoot3>
                                <dateLibrary>java8</dateLibrary>
<!--                                <useOpenApiNullable>false</useOpenApiNullable>-->
<!--                                <openApiNullable>false</openApiNullable>-->
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

##### Steps to reproduce

1. Build the spec

**Comment by wing328** [comment]
> Additional (required, it seems?) dependencies for plugin are not listed in docs, so I believe it's a bug.

Does it work fine with the CLI instead?

**Comment by aabdelli03** [comment]
@Haarolean i've got this issue when upgrading jdk11 to jdk17 with swagger-annotations version 1.6.9
How did you resolve this plllzzz

**Comment by Haarolean** [comment]
@aabdelli03 hey! I've fixed this by getting rid of OpenAPI 😄

**Comment by aabdelli03** [comment]
@Haarolean oh i don't have that chance. 
I get this error only on jenkis but not in my local for all the generated classes from the swagger
package io.swagger.v3.oas.annotations.media does not exist
Does someone else resolved that problem pllz

**Comment by gtsystem** [comment]
Still happening in v7.7.0. Also it seems to be related to #11734

**Comment by Zsupi** [comment]
Could someone find a workaround or a fix for this issue?

**Comment by eliancode** [comment]
In my case, I had to add a few dependencies:
io.swagger.core.v3 -> swagger-annotations
jakarta.validation -> jakarta.validation-api
org.openapitools -> jackson-databind-nullable

In maven:
`	<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.2.27</version>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>0.2.6</version>
		</dependency>`

**Comment by kevin-li-klw** [comment]
would lower the version of openapi-generator-maven-plugin work in this case?

**Comment by kevin-li-klw** [comment]
@Haarolean , what is your springboot version?
