### ISSUE TITLE
[BUG][Swift] Generated code won't compile in Swift 6

### ISSUE THREAD

**Issue by r3econ** [OpenAPITools/openapi-generator#19366]
##### Description

The swift5 generator generates code that won't compile under Swift 6. All static variables generate. This can be already seen as a warning when _Strict Concurrency_ mode is activated in the project:

```
Reference to class property 'basePath' is not concurrency-safe because it involves shared
mutable state; this is an error in Swift 6
```

1. Is there a generator that generates Swift 6 code. If not, are there any plans to implement it?
2. Where can we find the source code of the Swift 5 generator? I can't find it in this repo nor in the [docs](https://openapi-generator.tech/docs/generators/swift5). I am asking since potentially we could help develop the Swift 6 version of it

##### Generated code

<img width="1240" alt="SCR-20240816-kmzx" src="https://github.com/user-attachments/assets/05f86871-bc94-4d5e-b194-5a2bf4f60750">

##### Usage showing the warning

<img width="1175" alt="SCR-20240816-knol" src="https://github.com/user-attachments/assets/72872845-66b8-4b85-94e8-3953942b9ef3">

##### openapi-generator version

7.7.0

**Comment by 4brunu** [comment]
Hi, https://github.com/OpenAPITools/openapi-generator/pull/19621 was just merged, and it should fix this.
The new swift6 generator it's experimental, because we are open to receive feedback com the community on how to improve it.
So if you have any feedback, it's welcome.
All the static classes we moved to singletons to make the compiler happy.
Also we have a lot of @unchecked sendable.
I'm not super happy with those, and I hope that we receive improvements from the community on how to fix thoses, because I'm not sure yet on what's the best way to manage those.

**Comment by r3econ** [comment]
@4brunu I regenerated the client using the new `swift6` generator. Sadly, the problem persists:

![image](https://github.com/user-attachments/assets/ab70894c-7de7-41ee-8b46-5f6fab6ea0a2)

```
Reference to class property 'customHeaders' is not concurrency-safe because it involves shared mutable state
```

Many things were generated differently. However, the generated code that causes the error remains the same as in `swift5` version. The following static variables are the problem:

![image](https://github.com/user-attachments/assets/f065b7bb-dc80-4963-8bad-d8c6262d1168)

**Comment by r3econ** [comment]
I'm using:
```
openapi-generator-cli 7.9.0-SNAPSHOT
  commit : 2437d7f
  built  : -999999999-01-01T00:00:00+18:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

I did a reinstall using steps from the readme:
```
brew uninstall openapi-generator && brew install --HEAD openapi-generator
```

Looks like I'm using almost the latest version (from 2 hours ago 2437d7fa971bc5955d7d7f6d0f4512a4e7c30ca7)

**Comment by r3econ** [comment]
I'm using the following command to generate:
```
openapi-generator generate -i Common/MyAPI/myapi.json -g swift6 -o Common/MyAPI --model-name-prefix XXX --additional-properties=projectName=MyAPI,generateAliasAsModel=true
```

**Comment by 4brunu** [comment]
Something is not right. Can you try to build a jar from source and use the jar directly?
You can do that by checkout the master branch, run ./mvnw package and the jar will be located at `modules/openapi-generator-cli/target/openapi-generator-cli.jar`

**Comment by 4brunu** [comment]
This should now be fixed with the new swift6 generator that is available with the new released version.
If you still have this issue, please reopen this issue.
Thanks
