### ISSUE TITLE
[BUG] OneOf java classes not getting generated as part of codeGen in gradle plugin 4.0.0

### ISSUE THREAD

**Issue by samarthgupta437** [OpenAPITools/openapi-generator#2906]
When I generate sever stub for spec having OneOf tags,  the code generation gradle task is successful , but in the generated models package OneOf*.java classes are missing. 

I am using  org.openapitools:openapi-generator-gradle-plugin:4.0.0 for "jaxrs-jersey" generatorName.

For example for below YAML file class "**OneOfSofa1Sofa2**" is not getting generated , but it is referred for variable "**sofaStyle**" in generated class Home.java

`openapi: 3.0.0
servers:
- description: Controller URL
  url: https://localhost:8080/testApiDesign/
info:
  description: Apis
  version: "1.0.0"
  title: "Enum and Discriminator testing"
  termsOfService: 'https://www.appdynamics.com/terms/'
  contact:
    email: demo@demo.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
- name: home
  description: Manage your home
  externalDocs:
    description: Find out more
    url: 'https://www.home.com'
paths:
  /home :
    post:
      tags:
      - home
      summary: Create a new home
      description: Creates a new home for given payload and returns the ID
      operationId: createHome
      responses:
        '201':
          description: Home created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Home'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      requestBody:
        $ref: '#/components/requestBodies/Home'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    Home:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Names'
        sofaStyle:
          oneOf:
          - $ref: '#/components/schemas/Sofa1'
          - $ref: '#/components/schemas/Sofa2'
          discriminator:
            propertyName: styleType
      required:
      - name
      - sofaStyle
    Names:
      type: object
      properties:
        name:
          type: string
          enum:
          - "home1"
          - "home2"
      required:
      - name
    SofaStyleType:
      type: object
      properties:
        styleType:
          type: string
      required:
      - styleType
      discriminator:
        propertyName: styleType
    Sofa1:
      allOf:
      - $ref: '#/components/schemas/SofaStyleType'
      - type: object
        properties:
          identifier:
            type: string
            enum:
            - "big"
    Sofa2:
      allOf:
      - $ref: '#/components/schemas/SofaStyleType'
      - type: object
        properties:
          identifier:
            type: string
            enum:
            - "small"
  requestBodies:
    Home:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Home'`

**Comment by judgej** [comment]
`OneOf` classes also not being generated for the PHP client. The expected class name seems appropriate\ `OneOfType1Type2Etc` with each data type of reference name listed, but the classes are just not created.

I'm mentioning this in case it's a problem with the underlying spec parsing rather than the language generator.

**Comment by audricschiltknecht** [comment]
For Java, I'm hitting the same issues using both the CLI and the gradle plugin: Oneof classes are not generated.
Also the case for Python code, I'm guessing this is more of an general issue than a language-specific one.

**Comment by ChintanSK** [comment]
Facing the same problem with the java maven plugin: OneOf* classes are not generated, hence failing the compile task in the maven build.

**Comment by alfirin** [comment]
Same issue here.

**Comment by Frontrider** [comment]
Same here.

**Comment by Frontrider** [comment]
The base schema that it uses to generate from does not seem to have `oneOf`, `anyOf`,`allOf` in it. I can't even generate examples with those.

**Comment by wackykid** [comment]
so when is this going to be resolved? I am using the latest openapi-generator and I too get this issue. luckily I am doing the design of the API so I can redesign my API to NOT use oneOf to avoid this.

**Comment by giannisla** [comment]
do we know when is it going to be resolved?

**Comment by gigaga** [comment]
Same for me for generating Java server.

**Comment by Alex118** [comment]
Same issue here. This is a critical blocker for using openapi generator in our project as we deal with polymorphic APIs. 

Has anyone at least found a workaround for this?

**Comment by Frontrider** [comment]
A workaround is to create those classes manually.

**Comment by wackykid** [comment]
> A workaround is to create those classes manually.

any examples on how these classes should look like..?

**Comment by Frontrider** [comment]
Depends on your setup. We just extend one of the classes that it generated as the parent of the ones we need, then implement all of the unique parts. That will look like the class we need.

**Comment by ghilainm** [comment]
Same issue here using the spring-cloud generator 4.0.0. Any plan to fix this or do you believe it is not meant to be fixed?

**Comment by steeeve1510** [comment]
I'm having the same issue with the jaxrs-cxf generator. Currently we are using the version 3.3.4. There the OneOf... Class doesn't get rendered. Instead Object is used. This works for our use case.

**Comment by nickshoe** [comment]
Same issue with a JHipster API-first development project, which uses:
`<openapi-generator-maven-plugin.version>4.1.3</openapi-generator-maven-plugin.version>`

**Comment by dbaltor** [comment]
It has seemingly fixed by this PR #5120

**Comment by bspies-work** [comment]
We are using the openapi-generator-gradle plugin to do the generation, and seeing this issue too with version 4.3.0. Tried the 5.0.0-beta version (released June 2020) and still seeing this issue, so either that merge didn't make it in to either version, or it is not fixed.

**Comment by karllosernnesto-vakt** [comment]
Im having some issue... using **_openapi-generator-maven-plugin_** at 4.3.1 version. So do u have any updates regarding this issue?

**Comment by wing328** [comment]
Currently, only `java` client (`jersey2` library) generator has better support for oneOf and anyOf. Please give it a try to see if you've any feedback on the implementation.

**Comment by rj93** [comment]
@wing328 I have tried using the `jersey2` library, but I it is complaining that it is unable to find `symbol: class JsonTypeInfo` and `class JsonSubTypes`. I have the dependency:

```
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.11.2</version>
</dependency>
```

The generated `OneOf` class doesn't seem to be adding the imports for them:

```
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-22T14:51:06.694+01:00[Europe/London]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "", visible = true)
@JsonSubTypes({
})

public interface TransactionsAllOfTransactionsOneOf  {
}
```

Any ideas?

**Comment by Frontrider** [comment]
I think we also had some import problems, but I'm not sure, as I'm not the one directly working with these.

**Comment by thSoft** [comment]
A (not type-safe) workaround is to enumerate the class names generated from oneOf types in the following command line switches when running the generator:
`--language-specific-primitives=OneOfTypeATypeB,OneOfTypeCTypeB --type-mappings=OneOfTypeATypeB=java.lang.Object,OneOfTypeCTypeB=java.lang.Object`

**Comment by sann3** [comment]
In 7.8.0, only one class is getting generated in oneOf not both. Any workaround/fix available ?

**Comment by sann3** [comment]
In 7.8.0, it is generating both classes for OneOf, means this is fixed ?
