### ISSUE TITLE
[BUG][Spring] generated api interface doesn't have @RequestParam annotation

### ISSUE THREAD

**Issue by t2y** [OpenAPITools/openapi-generator#3248]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I updated openapi-generator from 4.0.1 to 4.0.2. Then, I found generated api interface from same spec is different between 4.0.1 and 4.0.2.

For some reason, `@RequestParam` is not generated for api parameters. Here is an example.

* 4.0.1
```java
@ApiParam(value = "", allowableValues = "json, csv, tsv", defaultValue = "json")
@Valid
@RequestParam(value = "format", required = false, defaultValue = "json")
Format format
```

* 4.0.2
```java
@ApiParam(value = "", allowableValues = "json, csv, tsv", defaultValue = "json")
@Valid
Format format
```

##### openapi-generator version

4.0.2

##### OpenAPI declaration file content or url

My spec has multiple yaml configurations.

* openapi.yaml
```yaml
openapi: 3.0.2
info:
  title: info
  description: info
  version: 0.1.0

paths:
  /example/api:
    get:
      summary: summary
      description: desc
      operationId: getApi
      parameters:
      - $ref: '#/components/parameters/formatParam'
      responses:
        200:
          description: response
          content:
            application/json:
              schema:
                type: string

components:
  parameters:
    formatParam:
      description: set format to get data
      name: format
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/format'
```

* schemas.yaml
```yaml
components:
  schemas:
    format:
      description: normal api response format
      type: string
      enum: [json, csv, tsv]
      default: json
```

##### Command line used for generation

I use below gradle plugin with 2.18.1 to generate api code.

* https://github.com/int128/gradle-swagger-generator-plugin

The build.grade related to openapi is like this.
```
swaggerSources {
    openapi {
        inputFile = file('spec/openapi.yaml')
        code {
            language = 'spring'
            rawOptions = [
                '--import-mappings=inputStream=org.springframework.core.io.InputStreamResource',
                '--type-mappings=inputStream=org.springframework.core.io.InputStreamResource',
            ]
            configFile = file('spec/config.json')
            // dependsOn validation
        }
    }
}
```

##### Steps to reproduce

Generate api code for spring with 4.0.1 and 4.0.2. Then compare the api parameters of api interface.

##### Related issues/PRs

I couldn't find any similar issues.

**Comment by t2y** [comment]
I found some parameters have `@RequestParam` and some parameters doesn't.

**Comment by macjohnny** [comment]
@t2y can you give an example spec and point to the parameters that generate `@RequestParam` and those that dont?

**Comment by t2y** [comment]
@macjohnny Now I made a test environment to run openapi-generator cli for git bisect. I will investigate which revision affects this issue in this weekend.

Currently, my production spec is complicated, so I will try to create simple example spec if possible.

**Comment by t2y** [comment]
I confirmed 4.0.3 still has this issue.

**Comment by t2y** [comment]
I did git bisect. This revision is the first bad commit.

* https://github.com/OpenAPITools/openapi-generator/commit/146c1fb25530699661211bcdd92b76491902b4b7
* https://github.com/OpenAPITools/openapi-generator/issues/2655

**Comment by t2y** [comment]
@macjohnny I updated `openapi.yaml` in above description to be able to reproduce this issue.

In my environment, generated api interface has diff between 0d701b7ce9e21c9405cac5cf17facd48dba542fc and 146c1fb25530699661211bcdd92b76491902b4b7 as below. The `format` parameter doesn't have `@RequestParam` annotation. Could you confirm?

```diff
$ diff -u s3-good/src/main/java/org/openapitools/api/ExampleApi.java s3-bad/src/main/java/org/openapitools/api/ExampleApi.java
--- s3-good/src/main/java/org/openapitools/api/ExampleApi.java	2019-07-13 14:46:47.000000000 +0900
+++ s3-bad/src/main/java/org/openapitools/api/ExampleApi.java	2019-07-13 14:49:11.000000000 +0900
@@ -26,7 +26,7 @@
 import java.util.List;
 import java.util.Map;
 import java.util.Optional;
-@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-07-13T14:46:46.993+09:00[Asia/Tokyo]")
+@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-07-13T14:49:11.556+09:00[Asia/Tokyo]")

 @Validated
 @Api(value = "example", description = "the example API")
@@ -42,7 +42,7 @@
     @RequestMapping(value = "/example/api",
         produces = { "application/json" },
         method = RequestMethod.GET)
-    default ResponseEntity<String> exampleApiGet(@NotNull @ApiParam(value = "set query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "set format", allowableValues = "json, csv", defaultValue = "json") @Valid @RequestParam(value = "format", required = false, defaultValue="json") Format format) {
+    default ResponseEntity<String> exampleApiGet(@NotNull @ApiParam(value = "set query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "set format", allowableValues = "json, csv", defaultValue = "json") @Valid Format format) {
         return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

     }
```

**Comment by macjohnny** [comment]
@t2y thanks for the analysis
a workaround for your problem could be to inline the parameter, i.e.
```yaml
components:
    formatParam:
      description: set format
      in: query
      name: format
      required: false
      default: json
      description: response format
      enum:
        - json
        - csv
      type: string

```

I guess either `components.schemas` should not be used for query params or 
https://github.com/OpenAPITools/openapi-generator/blob/146c1fb25530699661211bcdd92b76491902b4b7/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2213
should be extended to also check that the type is `object`
@wing328 @jimschubert @jmini what is your opinion?

**Comment by t2y** [comment]
remind, @wing328 @jimschubert @jmini what do you think about above solution?

**Comment by jimschubert** [comment]
@t2y thanks for pinging. I'm very far behind on emails and didn't see the last mention in the thread.

It looks like `property.isModel` assignment could add an `&& !ModelUtils.isEnum(p)`? This function doesn't exist, but may be necessary for this case

**Comment by manderson23** [comment]
I also see missing `@RequestParam` with `date-time` format. 
```
- name: start
  in: query
  schema:
     type: string
     format: date-time
  required: true
  description: The start time.
```
If I delete `format` to have the parameter a `String` then `@RequestParam` is present.

**Comment by t2y** [comment]
@macjohnny @jimschubert This bug is critical for me, and block upgrading version. Do you have a plan to fix?

**Comment by macjohnny** [comment]
@t2y would you like to submit a PR with a fix?

**Comment by t2y** [comment]
@macjohnny I don't know the background this issue. But, I can try to fix and create a PR, so I will do it next week if no one will fix.

**Comment by macjohnny** [comment]
This would be very appreciated

**Comment by peyerroger** [comment]
Blocking for me as well. A fix would be highly appreciated.

**Comment by arrigod** [comment]
This is needed by me as well. A fix would be very appreciated.

**Comment by jorgerod** [comment]
This is needed by me as well. A fix would be highly appreciated.

**Comment by macjohnny** [comment]
@arrigod @peyerroger would you like to file a PR to fix this?

**Comment by peyerroger** [comment]
@macjohnny I'll try...

**Comment by t2y** [comment]
@peyerroger Sorry, I haven't started yet. Please!

**Comment by melissapalmer** [comment]
@wing328 @jimschubert @jmini @macjohnny   is the fix not just to remove the {{^isModel}} from the /JavaSpring/queryParams.mustache template? As suggested by @macjohnny at: https://github.com/OpenAPITools/openapi-generator/issues/2053#issuecomment-495561796

Test example at: https://github.com/melissapalmer/openapi-generator-cli showing working params and not working with template override .

**Comment by peyerroger** [comment]
@melissapalmer That was my first idea as well, but it would reintroduce [#2655](https://github.com/OpenAPITools/openapi-generator/issues/2655) this issue here.

Instead of ^isModel we could use #isPrimitiveType. I wrote a couple of test cases to ensure it's properly working and it does.

What I don't really understand is why this change was introduced [146c1fb](https://github.com/OpenAPITools/openapi-generator/commit/146c1fb25530699661211bcdd92b76491902b4b7)? Was the only reason the fix for [#2655](https://github.com/OpenAPITools/openapi-generator/issues/2655) or is there more behind this commit? Could we remove the following line? Or did this fix something else?
`property.isModel = ModelUtils.isModel(p);`
in [DefaultCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/42d6420400a036fd2215a7b19f57e3292fdf394d/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java)

@macjohnny Could you give me some advice on this?

**Comment by jimschubert** [comment]
@peyerroger correct, that commit was intended to fix #2655. I think there are two options.... first, we could add to the condition as I suggested previously, something like:

```
property.isModel = ModelUtils.isModel(p) &&
   !ModelUtils.isEnum(p) && // new method
   !ModelUtils.isPrimitive(p); //to be extra safe
```

Or second, we could revert that commit and reopen the bug.

**Comment by jimschubert** [comment]
I've opened #3855 with a proposed fix. Would someone from this thread be able to test it out and provide feedback?

**Comment by peyerroger** [comment]
Hi guys,

I created a PR as well ( #3857 ). Here's what I did:

- I reverted this [146c1fb](https://github.com/OpenAPITools/openapi-generator/commit/146c1fb25530699661211bcdd92b76491902b4b7), but kept the test to ensure that there's no regression on issue #2655
- I used isPrimitiveType instead of ^isModel in the mustache template. This seems to be a much simpler solution and a lot less invasive as the solution introduced in [146c1fb](https://github.com/OpenAPITools/openapi-generator/commit/146c1fb25530699661211bcdd92b76491902b4b7)
- I added a couple of tests to ensure enums, localdates and so on are working properly

Cheers,
Roger

**Comment by t2y** [comment]
@jimschubert #3855 was merged into 4.1.3, so this issue was fixed I think.

**Comment by nbrugger-tgm** [comment]
Why is the issue not closed?
Is the bug still there or isn't it tested?

**Comment by vi-verrone** [comment]
The bug is still there with 4.1.3, @RequestParam is not generated for $ref models.
