### ISSUE TITLE
[BUG][typescript-fetch] Schema with type array generates undefined function

### ISSUE THREAD

**Issue by gk4m** [OpenAPITools/openapi-generator#3278]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I'm generating a `typescript-fetch` client using OpenAPI Generator `4.0.2`. After running the generator, function `stringToJSON` is included in the output, but it is not defined.

##### openapi-generator version
4.0.2

##### OpenAPI declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "description": "MyApi",
    "title": "MyApi",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "schemes": ["http"],
  "paths": {
    "/test": {
      "put": {
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}

```

##### Command line used for generation
```
node_modules/.bin/openapi-generator generate -g typescript-fetch -i ./openapi.json -o ./src
```

##### Steps to reproduce
I've created a gist that should help to reproduce the issue.
```
git clone https://gist.github.com/gk4m/67045978063c7e2caf97fc8725620d62 bug-report
cd bug-report
yarn install
yarn generate
yarn test
```

You should see the following output:

```
src/apis/DefaultApi.ts:44:46 - error TS2304: Cannot find name 'stringToJSON'.

44             body: requestParameters.body.map(stringToJSON),
```

The source of the error can be found in `src/apis/DefaultApi.ts` which contains the following:
```ts
export interface TestPutRequest {
    body: Array<string>;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async testPutRaw(requestParameters: TestPutRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling testPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/test`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body.map(stringToJSON),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testPut(requestParameters: TestPutRequest): Promise<void> {
        await this.testPutRaw(requestParameters);
    }

}
```

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/1877

##### Suggest a fix
Function `stringToJSON` should be added to generated file.

**Comment by macjohnny** [comment]
cc @TiFu

**Comment by macjohnny** [comment]
@gk4m would you like to give it a try and implement a fix? see also https://github.com/OpenAPITools/openapi-generator/pull/2453

**Comment by dalinarkholin** [comment]
Sorry for the annoying bump, but any movement on this one? @wing328 @macjohnny

**Comment by macjohnny** [comment]
@dalinarkholin would you like to implement a fix for that? i can point you to the relevant files.

**Comment by macjohnny** [comment]
cc @Place1 @someone1

**Comment by dalinarkholin** [comment]
@macjohnny Was this included in 4.1.0? I still see the same behavior. `stringToJSON` function is undefined.

**Comment by macjohnny** [comment]
@dalinarkholin this should be inlcuded in 4.1.0
Can you post the relevant part of your spec?

**Comment by dalinarkholin** [comment]
@macjohnny my mistake. This is resolved.

**Comment by macjohnny** [comment]
thanks again to @someone1 for fixing this

**Comment by markspolakovs** [comment]
I'm still seeing this on 4.3.1. Here's a gist with a schema and the generated `models/Listen.ts`, invoked as `npx @openapitools/openapi-generator-cli generate -i openapi.json -g typescript-fetch -o gen`.

https://gist.github.com/markspolakovs/afd0bd3cdf6955a90fc1e75f60e166b1

**Comment by macjohnny** [comment]
@markspolakovs could you please open a new issue?

**Comment by markocevar** [comment]
Any workaround possible for this issue?

**Comment by wing328** [comment]
@markspolakovs did you try the latest master or stable version v5.0.1?

What do the actual code and expected code look like?

**Comment by markspolakovs** [comment]
@wing328 Can still reproduce on v5.0.1, [here's the input and output](https://gist.github.com/markspolakovs/314504233e8117bc2094291d1d9b3aaf).

On [line 40](https://gist.github.com/markspolakovs/314504233e8117bc2094291d1d9b3aaf#file-listen-ts-L40) the generator outputs syntactically invalid TypeScript (`'boolean' only refers to a type, but is being used as a value here.`).

**Comment by ssalimit** [comment]
For me this happens when I use v5.0.0-beta3 onwards, but it looks fine when using v5.0.0-beta2. Is there any possible workaround?

**Comment by jacek-rzrz** [comment]
I'm seeing seemingly the same problem on the 5.2.0 now:

JsonAPI spec:
```json
...
"included" : {
  "type" : "array",
  "description" : "...",
  "items" : {
    "oneOf" : [ {
      "type" : "object"
    }, {
      "type" : "boolean"
    }, {
      "type" : "string"
    }, {
      "type" : "number"
    } ]
  }
}
...
```

Typescript type looks like that:
```typescript
export interface V1BunnyBunnyId204409787 {
    included?: Array<object | boolean | string | number>;
}
```

And the generated `fromJSON` / `toJSON` functions are invalid:

```typescript
return {
    'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(object | boolean | string | numberFromJSON)),
};
```

**Comment by simPod** [comment]
Has anyone found any workaround? 6.2.1 and I see a lot of undefined functions like `stringToJSON` etc.

**Comment by rohanrajpal** [comment]
Facing the same issue here, shall post a workaround tho if I find one

**Comment by Holt59** [comment]
Any update in 2023? How is anyone using this generator if a simple `application/x-www-form-urlencoded` completely breaks it...

**Comment by wing328** [comment]
If anyone would like to contribute a fix or sponsor a fix, please reply to let us know.
