### ISSUE TITLE
[BUG] generated python client code cannot send object in multipart/form-data

### ISSUE THREAD

**Issue by itaru2622** [OpenAPITools/openapi-generator#8068]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
generated python client code cannot send object in Content-Type:multipart/form-data

generator version: latest master branch
yaml: modules/openapi-generator/src/test/resources/3_0/form-multipart-binary-array.yaml
tested API(operationId):  multipartMixed

generate python client code from the above yaml and make test app as described in generated doc (docs/MultipartApi.md).
the test app receives error before sending HTTP request to the server.
Error message says:
```bash
./test.py
Traceback (most recent call last):
  File "/tmp/tests/test.py", line 19, in <module>
    api_instance.multipart_mixed(file,  marker=marker)
  File "/tmp/tests/openapi_client/api_client.py", line 740, in __call__
    return self.callable(self, *args, **kwargs)
  File "/tmp/tests/openapi_client/api/multipart_api.py", line 218, in __multipart_mixed
    return self.call_with_http_info(**kwargs)
  File "/tmp/tests/openapi_client/api_client.py", line 802, in call_with_http_info
    return self.api_client.call_api(
  File "/tmp/tests/openapi_client/api_client.py", line 382, in call_api
    return self.__call_api(resource_path, method,
  File "/tmp/tests/openapi_client/api_client.py", line 192, in __call_api
    response_data = self.request(
  File "/tmp/tests/openapi_client/api_client.py", line 428, in request
    return self.rest_client.POST(url,
  File "/tmp/tests/openapi_client/rest.py", line 264, in POST
    return self.request("POST", url,
  File "/tmp/tests/openapi_client/rest.py", line 181, in request
    r = self.pool_manager.request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 155, in request_encode_body
    body, content_type = encode_multipart_formdata(
  File "/usr/local/lib/python3.9/site-packages/urllib3/filepost.py", line 90, in encode_multipart_formdata
    body.write(data)
TypeError: a bytes-like object is required, not 'dict'
```

##### openapi-generator version
latest master branch

##### OpenAPI declaration file content or url
modules/openapi-generator/src/test/resources/3_0/form-multipart-binary-array.yaml

##### Generation Details
python test app named 'test.py'

```python
#!/usr/bin/env python3
import time
import openapi_client
from openapi_client.api import multipart_api
from openapi_client.model.multipart_mixed_marker import MultipartMixedMarker
from pprint import pprint
configuration = openapi_client.Configuration(host="http://localhost")
with openapi_client.ApiClient(configuration) as api_client:
     api_instance = multipart_api.MultipartApi(api_client)
     file= open('./test.py', 'rb')
     marker = MultipartMixedMarker( name="name_example",)
     try:
          api_instance.multipart_mixed(file,  marker=marker)
     except openapi_client.ApiException as e:
          print("Exception when calling MultipartApi->multipart_mixed: %s\n" % e)
```

##### Steps to reproduce
docker run  -v ${PWD}:${PWD} -v ${PWD}/out:/out -w ${PWD} 
 openapitools/openapi-generator-cli  generate -g python  -i form-multipart-binary-array.yaml -o /out 

run test.py then got error.

##### Related issues/PRs
#2165  may be related and #2167 can fix this issue, but not sure. 

##### Suggest a fix
in case of object,  encode it in json and add 'content-type: application/json'  as described bellow:
```
Content-Disposition: form-data; name="marker"
Content-Type: application/json
{"name": "name_example"}
```

**Comment by spacether** [comment]
This was fixed in https://github.com/OpenAPITools/openapi-generator/pull/8437/files

**Comment by Poolmann** [comment]
Having the similar issues with multipart/form-data. Though it seems my problem wasn't fixed through the PR. I'm using `modules/openapi-generator/src/test/resources/3_0/form-multipart-binary-array.yaml` as well as the master version of the cli to generate a python client.

When running the client like:
```python
import openapi_client
from openapi_client.rest import ApiException
from pprint import pprint

# Defining the host is optional and defaults to http://localhost
# See configuration.py for a list of all supported configuration parameters.
configuration = openapi_client.Configuration(host="http://localhost")


# Enter a context with an instance of the API client
with openapi_client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = openapi_client.MultipartApi(api_client)
    file_buffer = open("audio.wav", "rb")
    file = file_buffer.read()

    try:
        api_instance.multipart_single(file=file)
    except Exception as e:
        print("Exception when calling MultipartApi->multipart_array: %s\n" % e)

file_buffer.close()
```
I get `Exception when calling MultipartApi->multipart_array: embedded null byte`.
Any idea why this happens?
Does this belong here, or should I open a new issue for this?
