### ISSUE TITLE
[JAVA] beta3 adds springfox import in spring generator

### ISSUE THREAD

**Issue by trks1970** [OpenAPITools/openapi-generator#8192]
##### Description

I have upgraded from beta2 to beta3 and the java spring code generated from the api yaml file contains the import:

`springfox.documentation.annotations.ApiIgnore`

but the compiler fails on this import.

##### openapi-generator version

beta3, was working in beta2

##### OpenAPI declaration file content or url

```yaml
paths:
  /endpoint:
    post:
      summary: Whatever
      tags:
        - endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Whatever'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Something'
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          $ref: '#/components/responses/InternalServerError'
```
##### Command line used for generation
mvn clean generate-sources

`<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>${version.plugin.openapi.generator}</version>
				<configuration>
					<generateModels>true</generateModels>
					<generateApi>true</generateApi>
					<generateSupportingFiles>true</generateSupportingFiles>
					<generateAliasAsModel>true</generateAliasAsModel>
					<generatorName>spring</generatorName>
					<generateApiDocumentation>true</generateApiDocumentation>
					<generateModelDocumentation>true</generateModelDocumentation>
					<generateApiTests>true</generateApiTests>
					<configOptions>
						<interfaceOnly>true</interfaceOnly>
						<serializableModel>true</serializableModel>
						<dateLibrary>java8</dateLibrary>
						<library>spring-boot</library>
						<ensureUniqueParams>false</ensureUniqueParams>
						<useBeanValidation>true</useBeanValidation>
					</configOptions>
					
				</configuration>
				<executions>
					<execution>
						<id>generate-model</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<modelPackage>whatever.api.model</modelPackage>
							<apiPackage>whatever.api.model</apiPackage>
							<invokerPackage>whatever.api.model</invokerPackage>
							<inputSpec>${project.build.resources[0].directory}/api/whatever.yaml</inputSpec>
						</configuration>
					</execution>
				</executions>
			</plugin>`

**Comment by CGavrila** [comment]
I have the exact same issue.

**Comment by CGavrila** [comment]
The problem seems to be coming from here: https://github.com/OpenAPITools/openapi-generator/blob/c974c512ff590c797db9f3e93c079017d65d3dcd/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L456

There are a few way around it: use `apiFirst=true`, `reactive=true` or add the Springfox dependency to your `pom.xml`. They might work for you, but they are not enough for my usecase.

**Comment by mimkorn** [comment]
Same here, ApiIgnore generated, unused, import failing

**Comment by sdoeringNew** [comment]
I'm getting sick of it. With every new version of the generator there is new stuff that's gonna be imported and can't be disabled.

The openapi-generator is a mature library and can't add those things randomly. Backwards compability shall be the main goal on every change.

Here it is doubly bad because who's using SpringFox after all the years of stagnation? It took them years to release their version 3.
I think springdoc-openapi is the current way to go. But the openapi-generator only supports SpringFox without chance of disabling it or changing it to springdoc-openapi.

**Comment by morphlne** [comment]
`ApiIgnore` import fixed in 5.3.0, [quick](https://github.com/morphlne/openapi-generator-demo) working sample
@wing328 @trks1970 please close

**Comment by llui2222** [comment]
it's still presents:

`import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.5.6"
	id("org.openapi.generator").version("5.3.0")
	id("io.spring.dependency-management") version "1.0.11.RELEASE"
	kotlin("jvm") version "1.5.31"
	kotlin("plugin.spring") version "1.5.31"
	kotlin("plugin.jpa") version "1.5.31"
}

group = "com.hometask"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

configurations {
	compileOnly {
		extendsFrom(configurations.annotationProcessor.get())
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("javax.validation:validation-api:2.0.1.Final")
	implementation("org.flywaydb:flyway-core")
	api("io.springfox:springfox-swagger2:3.0.0")
	api("io.springfox:springfox-swagger-ui:3.0.0")
	api("org.openapitools:jackson-databind-nullable:0.2.1")
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	compileOnly("org.projectlombok:lombok")
	runtimeOnly("com.h2database:h2")
	annotationProcessor("org.projectlombok:lombok")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}
val spec = "$rootDir/src/main/resources/openapi/api.yml"
val generatedSourcesDir = "$buildDir/generated/openapi"

openApiGenerate {
	generatorName.set("spring")

	inputSpec.set(spec)
	outputDir.set(generatedSourcesDir)

	apiPackage.set("org.openapi.example.api")
	invokerPackage.set("org.openapi.example.invoker")
	modelPackage.set("org.openapi.example.model")

	configOptions.set(mapOf(
		"dateLibrary" to "java8"
	))
}

sourceSets {
	getByName("main") {
		java {
			srcDir("$generatedSourcesDir/src/main/java")
		}
	}
}

tasks {
	val openApiGenerate by getting

	val compileJava by getting {
		dependsOn(openApiGenerate)
	}
}
tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "11"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
` 

the result of `gradle clean build` is:

> \build\generated\openapi\src\main\java\org\openapitools\configuration\OpenAPIDocumentationConfig.java:14: error: cannot find symbol
import springfox.documentation.spring.web.paths.RelativePathProvider;
                                               ^
  symbol:   class RelativePathProvider
  location: package springfox.documentation.spring.web.paths
