### ISSUE TITLE
[BUG][JAVA] Description

### ISSUE THREAD

**Issue by Ankhell** [OpenAPITools/openapi-generator#8599]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If path to OpenAPI 3 specification file contains spaces you get an error
```java
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')```
Everything generates just fine if there is no spaces and backslashes in path 

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: SOME REST API
  description: SOME REST API
  version: 1.0.3
servers:
  - url: /api
    description: current environment
  - url: http://localhost:8080/api
paths:
  /somePath:
    get:
      responses:
        200:
          description: Request OK.
          content:
            'text/plain':
              schema:
                type: string
```
##### Generation Details

```java -jar openapi-generator-cli-5.jar generate -i "C:\Idea Projects\dummy\dummy.yml -g java -o "C:\Idea Projects\dummy\results" --library rest-assured --api-package "com.example.dummy.api" --model-package "com.example.dummy.model" --invoker-package "com.example.dummy.invoker"```

everything works fine with
```java -jar openapi-generator-cli-5.jar generate -i "C:/IdeaProjects/dummy/dummy.yml -g java -o "C:/IdeaProjects/dummy/results" --library rest-assured --api-package "com.example.dummy.api" --model-package "com.example.dummy.model" --invoker-package "com.example.dummy.invoker"```

##### Steps to reproduce

- Try to generate sources from openAPI 3 spec file which path contains spaces or backslashes

**Comment by GORA-SAG** [comment]
Hi @Ankhell the problem is with OpenAPIDeserializer getServer(ObjectNode obj, String location, OpenAPIDeserializer.ParseResult result, String path) method as this is throwing array index out of bound exception.
Will fix this issue there, and it will automatically solve the above problem.
@wing328 can you please confirm the same.

**Comment by GORA-SAG** [comment]
seems the issue has been resolved, but we are using this version(swagger-parser-v3-2.0.23.jar) of jar in our project 
`catch (URISyntaxException var11) {
    String variable = value.substring(value.indexOf("{") + 1, value.indexOf("}")); //exception happened here
    if (server.getVariables() != null && !server.getVariables().containsKey(variable)) {
        result.warning(location, "invalid url : " + value);
    }
}`
updated code
`catch (URISyntaxException e) {
    result.warning(location,"invalid url : "+value);
	e.printStackTrace();
}`
@Ankhell as a workaround for the problem you can wrap the url using { } like {/api}

**Comment by juherr** [comment]
Potential duplicate of #8260

**Comment by vamshireddy09** [comment]
@GORA-SAG 
I'm using the CLI version of the tool to generate the SDK, I'm still facing the issue when having spaces in the input spec file path
Any suggestions?
