### ISSUE TITLE
[Java] Codegen fails with multiple response types

### ISSUE THREAD

**Issue by BBKolton** [OpenAPITools/openapi-generator#896]
##### Description

With two different defined response types for two different response codes, the generated file has a missing comma which crashes the build.

##### openapi-generator version

3.0.2

##### OpenAPI declaration file content or url

```yaml
  /health/deep:
    get:
      operationId: getHealthDeep
      summary: provides a deep endpoint healthcheck
      tags:
        - sometag
      responses: 
        200:
          description: Health OK
          content:
            text/plain:
              schema:
                type: string

        500:
          description: Failed Health Check Error Report
          content:
            application/json:
              schema:
                $ref: ../common/500.yaml
```

Deep in the target folder hierarchy, the `HealthApi.java` file has this section which throws a syntax error

```Java
    @ApiOperation(value = "provides a deep endpoint healthcheck", nickname = "getHealthDeep", notes = "", response = String.class, tags={ "sometag", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Health OK", response = String.class) })
    @RequestMapping(value = "/health/deep",
        produces = { "text/plain""application/json" },  // The issue is here, where a comma is ommitted
        method = RequestMethod.GET)
    default ResponseEntity<String> getHealthDeep() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```

##### Command line used for generation

mvn clean install

##### Steps to reproduce

Create an API document with a route.
Attempt to build the file using the `openapi-generator-maven-plugin`

##### Suggest a fix/enhancement

Ensure that multiple options for return types create commas inbetween them

(This is my first real issue I've reported, please let me know if you need more info!)

**Comment by jmini** [comment]
> (This is my first real issue I've reported, please let me know if you need more info!)

This is a great report for an issue.

If I remember well, something similar have already be reported and fixed. Can you try with the last released version: `3.2.2` instead of `3.0.2`?

**Comment by BBKolton** [comment]
Looks like the issue in the `HealthApi` file is resolved, but now `servicenameApi.java`, a generated file under `src/main/java/com/company/team/service/client/v1/serviceApi.java` fails. I assume a fix to the health api file was not propogated. 

```java
public com.squareup.okhttp.Call getHealthDeepCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = new Object();

        // create path and map variables
        String localVarPath = "/health/deep";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain""application/json" // same problem, comma omitted
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);
```

**Comment by melissapalmer** [comment]
I'm still experiencing a problem with the  way the ` produces =` of  `@RequestMapping` is being generated. 
Using yaml `openapi: 3.0.0` with `openapi-generator-maven-plugin`  version `3.3.4` 

In my case the code being generated is as follows:
```java
@ApiOperation(value = "Generate Report", nickname = "generateReportSync", notes = "Generate a report synchronously. This streams a report back to the requestor in the requested format. Use the [Content-Type] header to select the type of data stream to return.", response = Resource.class, tags={ "reports", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "OK", response = Resource.class),
        @ApiResponse(code = 400, message = "Invalid report parameters"),
        @ApiResponse(code = 401, message = "You are not authorized to generate the report"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Report template not found"),
        @ApiResponse(code = 500, message = "An unexpeced error occurred") })
    @RequestMapping(value = "/templates/{templateId}/generate",
        produces = "application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,text/html", // The issue is here: it should be an array of strings eg: {"", ""} 
        consumes = "application/json",
        method = RequestMethod.POST)
    default ResponseEntity<Resource> _generateReportSync(@ApiParam(value = "Report template unique identifier",required=true) @PathVariable("templateId") UUID templateId,@ApiParam(value = "Detail for the report to be generated, including parameters." ,required=true )  @Valid @RequestBody TemplateGenerateRequest templateGenerateRequest) {
        return generateReportSync(templateId, templateGenerateRequest);
    }

```

YAML used was: 
```
'/templates/{templateId}/generate':
    post:
      tags:
        - reports
      summary: Generate Report
      description: >-
        Generate a report synchronously. This streams a report back to the
        requestor in the requested format. Use the [Content-Type] header to
        select the type of data stream to return.
      operationId: generateReportSync
      parameters:
        - name: templateId
          description: Report template unique identifier
          in: path
          required: true
          example: 767518b7-2c4c-45e3-a520-bbbbe4a9f421
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateGenerateRequest'
        description: 'Detail for the report to be generated, including parameters.'
        required: true
      responses:
        '201':
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            text/csv:
              schema:
                type: string
            text/html:
              schema:
                type: string
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
```
