### ISSUE TITLE
[BUG] [DART] The default readme file has missing/misleading information

### ISSUE THREAD

**Issue by harsimranmaan** [OpenAPITools/openapi-generator#9186]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

5.1.1

##### Generation Details

```bash
java -jar ~/Downloads/openapi-generator-cli-5.1.0.jar generate -i trober.yaml -c config.yaml -g dart-dio-next -o trober_sdk -p pubVersion=1.1.1
```

##### Steps to reproduce

Generate a dart package with the dart-dio-next generator. Observe that the README.md has missing information for author and incorrect links to generated docs when published on pub.dev. eg: See https://pub.dev/packages/trober_sdk

##### Suggest a fix
Requires fixes to the README.md template. would send a PR with fixes.

**Comment by kuhnroyal** [comment]
@harsimranmaan Do you consider this solved with #9201?

**Comment by NANASHI0X74** [comment]
I've run into this as well... AFAICT the README examples and documentation generated are still wrong, for example it will tell me to do something like this:
```
var api_instance = new CompaniesApi();
```
while the companiesApi constructor requires two arguments.

So now instead I'm looking at the tests generated that I found via looking into the changed files in #8869:
https://github.com/kuhnroyal/openapi-generator/blob/8240a4fbafff6ddb93d1e992488efb4a6d0c391b/samples/client/petstore/dart-dio/petstore_client_lib/test/pet_api_test.dart#L14-L15
where did that file go in the current master btw?

**Comment by kuhnroyal** [comment]
That would be https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/dart-dio-next/petstore_client_lib_fake/test/pet_api_test.dart

If you are interested in providing a PR, this is the API-Doc template: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/libraries/dio/api_doc.mustache

**Comment by NANASHI0X74** [comment]
huh, was the dio generator's doc template already wrong before the migration to null safety? I just tried migrating from the default dart generator

**Comment by kuhnroyal** [comment]
Yes it was.
