### ISSUE TITLE
[BUG][OCaml] multiple errors in generated OCaml from Docker Engine API

### ISSUE THREAD

**Issue by MisterDA** [OpenAPITools/openapi-generator#9787]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm trying to generate the OCaml package for the Docker Remote API, v 1.41.

##### openapi-generator version

Latest master, 77e1ca56cf329bfb22b05f853587263fd0ff6503.

##### OpenAPI declaration file content or url

https://docs.docker.com/engine/api/v1.41.yaml

##### Generation Details

```
File "src/apis/config_api.mli", line 8, characters 43-45:
8 | val config_create : body:UNKNOWN_BASE_TYPE -> unit -> Id_response.t Lwt.t
                                               ^^
Error: Syntax error
File "src/apis/container_api.mli", line 13, characters 46-48:
13 | val container_create : body:UNKNOWN_BASE_TYPE -> ?name:string -> unit -> Container_create_response.t Lwt.t
                                                   ^^
Error: Syntax error
File "src/apis/secret_api.mli", line 8, characters 43-45:
8 | val secret_create : body:UNKNOWN_BASE_TYPE -> unit -> Id_response.t Lwt.t
                                               ^^
Error: Syntax error
File "src/apis/service_api.mli", line 8, characters 44-46:
8 | val service_create : body:UNKNOWN_BASE_TYPE -> ?x_registry_auth:string -> unit -> Service_create_response.t Lwt.t
                                                ^^
Error: Syntax error
File "src/apis/image_api.ml", line 13, characters 69-72:
13 |     let uri = Request.maybe_add_query_param uri "all" string_of_bool all in
                                                                          ^^^
Error: This expression has type 'a t list -> 'a list t
       but an expression was expected of type bool option
File "src/apis/plugin_api.ml", line 22, characters 52-56:
22 |     Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
                                                         ^^^^
Error: This expression has type 'a -> Cohttp_lwt.Body.t
       but an expression was expected of type Cohttp_lwt.Body.t
File "src/models/system_data_usage_response.ml", line 11, characters 16-23:
11 |     containers: Array.t list;
                     ^^^^^^^
Error: The type constructor Array.t expects 1 argument(s),
       but is here applied to 0 argument(s)
```

##### Steps to reproduce

Using OCaml 4.12.

```cmd
# have build latest openapi-generator
java -jar openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i https://docs.docker.com/engine/api/v1.41.yaml -g ocaml -o ../ocaml-docker-api
cd ../ocaml-docker-api
dune build @all
```

##### Related issues/PRs

- [ ] The `UNKNOWN_BASE_TYPE` was already reported at https://github.com/OpenAPITools/openapi-generator/issues/8398.

##### Suggest a fix

ping @cgensoul @davesnx.

**Comment by wing328** [comment]
I've merged some fixes to the latest master and could no longer repeat the issue. Please pull the latest master to give it a try.

**Comment by MisterDA** [comment]
Thanks for your work, but it's still not quite right. The generated code doesn't type-check. Here is a Dockerfile for reproductibility (using latest master 3a102e0):

```dockerfile
FROM ocaml/opam:debian-11-ocaml-4.14
RUN sudo apt-get install -y default-jdk
RUN opam-2.1 install -y cohttp-lwt-unix yojson ppx_deriving_yojson dune
RUN git clone --recursive https://github.com/openapitools/openapi-generator.git
WORKDIR openapi-generator
RUN git fetch origin && git reset --hard 3a102e0e5b6f9a316d06e8e7062a3a9112041e09
RUN ./mvnw clean install
RUN java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
    -i https://docs.docker.com/engine/api/v1.41.yaml \
    -g ocaml \
    -o /var/tmp/ocaml_api_client
WORKDIR /var/tmp/ocaml_api_client
RUN opam-2.1 exec -- dune build @all
```

It fails typechecking with:
```
File "src/apis/image_api.ml", line 13, characters 69-72:
13 |     let uri = Request.maybe_add_query_param uri "all" string_of_bool all in
                                                                          ^^^
Error: This expression has type 'a t list -> 'a list t
       but an expression was expected of type bool option
File "src/apis/plugin_api.ml", line 22, characters 52-56:
22 |     Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
                                                         ^^^^
Error: This expression has type 'a -> Cohttp_lwt.Body.t
       but an expression was expected of type Cohttp_lwt.Body.t
File "src/apis/container_api.ml", line 112, characters 63-66:
112 |     let uri = Request.add_query_param uri "all" string_of_bool all in
                                                                     ^^^
Error: This expression has type 'a t list -> 'a list t
       but an expression was expected of type bool
```

**Comment by MisterDA** [comment]
I've fixed one of the bugs, but this one

```
File "src/apis/plugin_api.ml", line 22, characters 52-56:
22 |     Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
                                                         ^^^^
Error: This expression has type 'a -> Cohttp_lwt.Body.t
       but an expression was expected of type Cohttp_lwt.Body.t
```

comes from [here](https://github.com/OpenAPITools/openapi-generator/blob/3a102e0e5b6f9a316d06e8e7062a3a9112041e09/modules/openapi-generator/src/main/resources/ocaml/api-impl.mustache#L44-L46):

```
{{#bodyParams}}
    let body = Request.{{#isFreeFormObject}}write_json_body{{/isFreeFormObject}}{{#isByteArray}}write_string_body{{/isByteArray}}{{^isFreeFormObject}}{{^isByteArray}}write_as_json_body{{/isByteArray}}{{/isFreeFormObject}} {{> to_json}} {{{paramName}}} in
{{/bodyParams}}
```

The generated code is missing one argument, the converter to `Yojson.Safe.t`, which is probably the identity function in this case `(fun x -> x)`.

```ocaml
let body = Request.write_as_json_body  input_stream in
Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
```
